type EnvKeys =
  | 'API_PORT'
  | 'API_HOST'
  | 'DB_SOKRATES_NAME'
  | 'DB_SOKRATES_HOST'
  | 'DB_SOKRATES_DIALECT'
  | 'DB_SOKRATES_USERNAME'
  | 'DB_SOKRATES_PASSWORD'
  | 'GOOGLE_OAUTH_REDIRECT_URI'
  | 'GOOGLE_OAUTH_AUTH_URI'
  | 'GOOGLE_OAUTH_CLIENT_ID'
  | 'GOOGLE_OAUTH_CLIENT_SECRET'
  | 'GOOGLE_OAUTH_TOKEN_URI'
  | 'JWT_SECRET_KEY'
  | 'JWT_EXPIRATION'
  | 'SESSION_SECRET_KEY'

export function getEnv(key: EnvKeys) {
  return process.env[key] as string
}
