apiVersion: v1
kind: PersistentVolume
metadata:
  name: __CI_PROJECT_NAME__-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/data/wgs/binus-be'

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __CI_PROJECT_NAME__-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
